const projects = [
  {
    title: "The Lotus Cafe",
    thumbnail: "images/lotusCafe.png",
    description:
      "This is a website for a fictional restaurant, The Lotus Cafe. It is a simple website that was created as an exercise in responsive layout design. The text was generated by ChatGPT and the images are all free stock photos.",
    link: "http://github.com",
  },
  {
    title: "Lucky Shrub Landscaping",
    thumbnail: "images/shrub.png",
    description:
      "This is a website for a fictional landscaping company based in Arizona. It features southwest style imagery and photos, and includes an image slideshow and a contact form.",
    link: "http://github.com",
  },
  {
    title: "Astronomy Photo Randomizer",
    thumbnail: "images/apod.png",
    description:
      "This project utilizes the NASA Astronomy Photo of the Day API to generate and display a random photo. This was an excersize in using APIs to pull and display data on a web page.",
    link: "http://github.com",
  },
];

function ProjectCard({ project }) {
  return (
    <div className="galleryCard">
      <img src={project.thumbnail} alt={project.title} className="galleryImg" />
      <h3>{project.title}</h3>
      <p>{project.description}</p>
      <a href={project.link} target="_blank">
        Link to GitHub
      </a>
    </div>
  );
}

export default function Gallery() {
  return (
    <div className="container">
      <h2>Portfolio</h2>
      <div className="gallery">
        <ProjectCard project={projects[0]} />
        <ProjectCard project={projects[1]} />
        <ProjectCard project={projects[2]} />
      </div>
    </div>
  );
}
